### ISSUE TITLE
Redux logo in the footer should link to the redux website

### ISSUE THREAD

**Issue by matteo-hertel** [georgegillams/georgegillams.co.uk#112]
In the footer, there is a single image with logos for both react and redux, going to the url, given the two are different projects the two logos should be separated and link to the correct websites.

Even better the svg version of the logo could be used

**Comment by georgegillams** [comment]
Noted, good Sir.
I would be delighted to rectify this most imminently 😂

**Comment by matteo-hertel** [comment]
![image](https://user-images.githubusercontent.com/3579758/114299156-bd416300-9ab1-11eb-9da6-eb325729d720.jpeg)

Immediately indeed 🤣
